// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmrysmofssolvteywfrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptcnlzbW9mc3NvbHZ0ZXl3ZnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzkxOTUsImV4cCI6MjA2ODg1NTE5NX0.wxelVEw52C9V3LNTWq-EBNLa6kGTZNbTJpvxxBch1f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});